language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: HM/2bVm4fUt1IrxZ3oscfGTddVWMVArgJfFCmsIY1LKZWBJ8Kz3ViqCau3KVgmFSfuHAvD01RrEOB4zzKRzYPdbkfRZREx+PXSAj4gRM8MtUyr2Z0n30OBB8SWfqoTumQLR5TevxqSrng0QE7BDKncpQXwaRGuJ5HiMU8hSAHLM=
  app: tune-bucket
  on:
    repo: jobbogamer/tune-bucket
